apiVersion: v1
kind: Secret
metadata:
  name: vendas-veiculo-service-secret
type: Opaque
stringData:
  db-username: "postgres"
  db-password: "postgres_sales_password_placeholder"
  jwt-secret: "my_very_long_shared_jwt_secret_m2m_placeholder"
  hmac-secret: "my_very_long_hmac_webhook_secret_placeholder"
