apiVersion: v1
kind: Service
metadata:
  name: vendas-veiculo-service
  labels:
    app: vendas-veiculo-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: vendas-veiculo-service
  type: ClusterIP
